apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: new-replica-set
spec:
  replicas: 4
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
       name: frontend
      labels:
       tier: frontend
    spec:
      containers:
      - name: busybox
        image: busybox