apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: voting-app
  name: voting-app-deployment
  labels:
    app: demo-voting-app
spec:
  selector:
    matchLabels:
      name: voting-app-pod
      app:  demo-voting-app
  template:
    metadata:
      name: voting-app-pod
      labels:
        name: voting-app-pod
        app:  demo-voting-app
    spec:
      containers:
       -  name: voting-app-pod
          image: dockersamples/examplevotingapp_vote
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80