apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: voting-app
  name: worker-deployment
  labels:
    app: demo-voting-app
spec:
  selector:
    matchLabels:
      name: worker-pod
      app:  demo-voting-app
  template:
    metadata:
      name: worker-pod
      labels:
        name: worker-pod
        app:  demo-voting-app
    spec:
      containers:
       -  name: worker-pod
          image: dockersamples/examplevotingapp_worker
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"