apiVersion: v1
kind: Service
metadata:
  name: results-service
  namespace: voting-app
  labels:
     app: demo-voting-app
spec:
  selector:
    name: results-app-pod
    app: demo-voting-app
  ports:
  - port: 80
    targetPort: 80
