apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  namespace: voting-app
  labels:
    name: voting-app-pod
    app: demo-voting-app
spec:
  containers:
  - name: results-app
    image:   dockersamples/examplevotingapp_vote
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80