apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  namespace: voting-app
  labels:
    name: worker-pod
    app:  demo-voting-app
spec:
  containers:
  - name: worker-pod
    image: dockersamples/examplevotingapp_worker
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
